### ISSUE TITLE
should -keep subclasses of android.content.ContentProvider

### ISSUE THREAD

**Issue by timbertson** [jberkel/android-plugin#10]
Proguard is stripping my ContentProvider implementor from the generated jar / apk. It looks like adding the following should work, but it doesn't seem to help:

```
"-keep public class * extents android.content.ContentProvider" ::
```

(in AndroidProject.scala, alongside all the other -keep flags)

**Comment by lolsborn** [comment]
Fixed in http://github.com/jberkel/android-plugin/commit/d8a2925f1e0b1e3894504469e4de8f0169372ffa

**Comment by timbertson** [comment]
I'm afraid this still doesn't seem to work. I did a publish-local, and changed my Plugins.scala line to:

```
val android = "org.scala-tools.sbt" % "sbt-android-plugin" % "0.4.2"
```

but after an sbt update and a rebuild, it still strips out the ContentProvider
